### ISSUE TITLE
UI Needs rework

### ISSUE THREAD

**Issue by florin-bizgan** [florin-bizgan/Project_Crypto#5]
- [ ] #5
- [x] #8 Form has to undergoo an major rework so it can be easier to interact with.
 - [x] #7 At the moment market_cycle.png is not mobile friendly
 - [ ] #6 Blog page needs content or has to be removed
